version: "3.8"

services:
  test-db:
    image: mongo:latest
    container_name: test-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
    ports:
      - "${MONGODB_EXPOSE_PORT}:${MONGODB_DOCKER_PORT}"
    volumes:
      - db_test:/data/db
  test-backend:
    depends_on:
      - test-db
    container_name: test-backend
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASS=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db_test: